use std::collections::BTreeMap;
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("manifest directory"));
    let unicode_dir = manifest.join("unicode/15.1.0");
    let case_folding = unicode_dir.join("CaseFolding.txt");
    let prop_list = unicode_dir.join("PropList.txt");

    println!("cargo:rerun-if-changed={}", case_folding.display());
    println!("cargo:rerun-if-changed={}", prop_list.display());

    let folds = parse_case_folding(&case_folding);
    let whitespace = parse_white_space(&prop_list);
    assert_eq!(
        whitespace.len(),
        25,
        "Unicode 15.1.0 White_Space must contain exactly 25 code points"
    );

    let mut generated = String::from("// @generated by build.rs from Unicode 15.1.0 UCD inputs.\n");
    generated.push_str("pub const UNICODE_VERSION: (u8, u8, u8) = (15, 1, 0);\n");
    generated.push_str("pub const WHITE_SPACE: &[u32] = &[\n");
    for code_point in whitespace {
        let _ = writeln!(generated, "    0x{code_point:04X},");
    }
    generated.push_str("];\n\n");
    generated.push_str("pub const CASE_FOLD: &[(u32, &[u32])] = &[\n");
    for (source, mapping) in folds {
        let rendered = mapping
            .iter()
            .map(|code_point| format!("0x{code_point:04X}"))
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(generated, "    (0x{source:04X}, &[{rendered}]),");
    }
    generated.push_str("];\n");

    let output = PathBuf::from(env::var_os("OUT_DIR").expect("output directory"))
        .join("unicode_15_1_generated.rs");
    fs::write(output, generated).expect("write generated Unicode table");
}

fn parse_case_folding(path: &PathBuf) -> BTreeMap<u32, Vec<u32>> {
    let source = fs::read_to_string(path).expect("read CaseFolding.txt");
    assert!(
        source.contains("CaseFolding-15.1.0.txt"),
        "unexpected CaseFolding.txt version"
    );

    let mut mappings = BTreeMap::new();
    for (line_number, line) in source.lines().enumerate() {
        let line = line
            .split('#')
            .next()
            .expect("split comment")
            .trim()
            .trim_end_matches(';')
            .trim();
        if line.is_empty() {
            continue;
        }
        let fields = line.split(';').map(str::trim).collect::<Vec<_>>();
        assert_eq!(
            fields.len(),
            3,
            "CaseFolding.txt line {} has unexpected field count",
            line_number + 1
        );
        if !matches!(fields[1], "C" | "F") {
            continue;
        }
        let source = parse_code_point(fields[0], "CaseFolding.txt", line_number + 1);
        let mapping = fields[2]
            .split_whitespace()
            .map(|value| parse_code_point(value, "CaseFolding.txt", line_number + 1))
            .collect::<Vec<_>>();
        assert!(
            !mapping.is_empty(),
            "CaseFolding.txt line {} has an empty mapping",
            line_number + 1
        );
        assert!(
            mappings.insert(source, mapping).is_none(),
            "CaseFolding.txt has duplicate C/F mapping for U+{source:04X}"
        );
    }
    assert!(
        mappings.len() > 1_000,
        "CaseFolding.txt mapping is incomplete"
    );
    mappings
}

fn parse_white_space(path: &PathBuf) -> Vec<u32> {
    let source = fs::read_to_string(path).expect("read PropList.txt");
    assert!(
        source.contains("PropList-15.1.0.txt"),
        "unexpected PropList.txt version"
    );

    let mut values = Vec::new();
    for (line_number, line) in source.lines().enumerate() {
        let line = line.split('#').next().expect("split comment").trim();
        if line.is_empty() {
            continue;
        }
        let fields = line.split(';').map(str::trim).collect::<Vec<_>>();
        assert_eq!(
            fields.len(),
            2,
            "PropList.txt line {} has unexpected field count",
            line_number + 1
        );
        if fields[1] != "White_Space" {
            continue;
        }
        let (start, end) = match fields[0].split_once("..") {
            Some((start, end)) => (
                parse_code_point(start, "PropList.txt", line_number + 1),
                parse_code_point(end, "PropList.txt", line_number + 1),
            ),
            None => {
                let value = parse_code_point(fields[0], "PropList.txt", line_number + 1);
                (value, value)
            }
        };
        assert!(
            start <= end,
            "PropList.txt line {} has a reversed range",
            line_number + 1
        );
        values.extend(start..=end);
    }
    values.sort_unstable();
    values.dedup();
    values
}

fn parse_code_point(value: &str, source: &str, line_number: usize) -> u32 {
    let code_point = u32::from_str_radix(value, 16)
        .unwrap_or_else(|_| panic!("{source} line {line_number} has invalid code point {value}"));
    assert!(
        char::from_u32(code_point).is_some(),
        "{source} line {line_number} has non-scalar code point {value}"
    );
    code_point
}
